### ISSUE TITLE
SystemCallError when requiring win32/file and win32/daemon

### ISSUE THREAD

**Issue by ferfebles** [djberg96/win32-file#5]
I found an error after installing win32-file when requiring win32/file and win32/daemon
Tested in Windows 8.1, ruby 2.0.0p451 (2014-02-24) [i386-mingw32]

```
C:\>irb
DL is deprecated, please use Fiddle
irb(main):001:0> require 'win32/file'
=> true
irb(main):002:0> require 'win32/daemon'
SystemCallError: The data area passed to a system call is too small - GetTokenInformation
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-stat-1.5.2/lib/win32/file/stat.rb:827:in `get_current_process_sid'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-stat-1.5.2/lib/win32/file/stat.rb:81:in `initialize'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-0.8.0/lib/win32/file.rb:426:in `new'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-0.8.0/lib/win32/file.rb:426:in `file?'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:76:in `block (2 levels) in contains_requirable_file?'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:76:in `each'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:76:in `any?'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:76:in `block in contains_requirable_file?'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:74:in `each'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:74:in `any?'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:74:in `contains_requirable_file?'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:943:in `block in find_inactive_by_path'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:942:in `each'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:942:in `find'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:942:in `find_inactive_by_path'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems.rb:185:in `try_activate'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from (irb):2
        from C:/Ruby200/bin/irb:12:in `<main>'irb(main):003:0>
```

**Comment by djberg96** [comment]
@ferfebles What is the output of "gem list win32-file" and "gem list ffi" ? I was unable to reproduce this on Windows 8.

**Comment by ferfebles** [comment]
```
C:\>gem list ffi

*** LOCAL GEMS ***

autotest-suffix (1.1.0)
ffi (1.9.10 x86-mingw32, 1.9.0 x86-mingw32)

C:\>gem list win32-file

*** LOCAL GEMS ***

win32-file (0.8.0)
win32-file-stat (1.5.2)

C:\>gem list win32-service

*** LOCAL GEMS ***

win32-service (0.8.7)

C:\>
```

**Comment by mlr-msft** [comment]
I get a similar error on my own system (Windows 10).

```
work $ ruby --version
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
```

My backtrace:

```
SystemCallError: The data area passed to a system call is too small. - GetTokenInformation
.../vendor/bundle/ruby/2.2.0/gems/win32-file-stat-1.5.3/lib/win32/file/stat.rb:827:in `get_current_process_sid'
.../vendor/bundle/ruby/2.2.0/gems/win32-file-stat-1.5.3/lib/win32/file/stat.rb:81:in `initialize'
.../vendor/bundle/ruby/2.2.0/gems/win32-file-0.8.0/lib/win32/file.rb:449:in `new'
.../vendor/bundle/ruby/2.2.0/gems/win32-file-0.8.0/lib/win32/file.rb:449:in `mtime'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/file_task.rb:22:in `timestamp'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/file_task.rb:16:in `needed?'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:229:in `format_trace_flags'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:182:in `block in invoke_with_call_chain'
C:/Users/mirobert/AppData/Local/scoop/apps/ruby/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:209:in `block in invoke_prerequisites'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `each'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `invoke_prerequisites'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
C:/Users/mirobert/AppData/Local/scoop/apps/ruby/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:209:in `block in invoke_prerequisites'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `each'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `invoke_prerequisites'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
C:/Users/mirobert/AppData/Local/scoop/apps/ruby/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:209:in `block in invoke_prerequisites'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `each'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `invoke_prerequisites'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
C:/Users/mirobert/AppData/Local/scoop/apps/ruby/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `each'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block in top_level'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:78:in `block in run'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
.../vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
.../vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'
.../vendor/bundle/ruby/2.2.0/bin/rake:23:in `<main>'
```

**Comment by djberg96** [comment]
@mlr-msft Ok, I see the issue. I'll have a fix out by this weekend. Thanks for the report!

**Comment by djberg96** [comment]
@ferfebles @mlr-msft I went ahead and updated it tonight. Should work now with 1.5.4. Please upgrade.

**Comment by mlr-msft** [comment]
Confirmed fixed. Thanks!
