### ISSUE TITLE
Windows XP error: 'CreateSymbolicLinkW' not found in [kernel32.dll]

### ISSUE THREAD

**Issue by ferfebles** [djberg96/win32-file#6]
Error when requiring win32/file. It seems that "CreateSymbolicLinkW (and possibly others) are not supported in Windows XP" https://github.com/rust-lang/rust/issues/11950.

```
C:\>irb
irb(main):001:0> require 'win32/file'
FFI::NotFoundError: Function 'CreateSymbolicLinkW' not found in [kernel32.dll]
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi/library.rb:261:in `attach_function'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-0.8.0/lib/win32/file/functions.rb:12:in `attach_pfunc'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-0.8.0/lib/win32/file/functions.rb:18:in `<module:Functions>'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-0.8.0/lib/win32/file/functions.rb:3:in `<module:File>'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-0.8.0/lib/win32/file/functions.rb:2:in `<module:Windows>'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-0.8.0/lib/win32/file/functions.rb:1:in `<top (required)>'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-0.8.0/lib/win32/file.rb:3:in `require_relative'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-0.8.0/lib/win32/file.rb:3:in `<top (required)>'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from (irb):1
        from C:/Ruby200/bin/irb:12:in `<main>'
```

**Comment by djberg96** [comment]
@ferfebles Yeah, I don't really support Windows XP, sorry. MS dropped support already.

**Comment by ferfebles** [comment]
Yes, I only have to convince my boss to reinstall our XPs with Linux :-(
Once again, thanks for your help.
